apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ejemplo
spec:
  host: ejemplo-curso.apps-crc.testing
  to:
    kind: Service
    name: docker-hello-world-svc
  port: 
    targetPort: 80
  