kind: Namespace
apiVersion: v1
metadata:
  name: curso
  labels:
    name: curso
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - sleep
    - "1000000"
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep-less
  namespace: curso
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - sleep
    - "10"
