apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: curso
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer