apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-02-17T14:09:57Z"
  labels:
    app: wordpress-pod
  name: wordpress-pod2
spec:
  containers:
  - args:
    - mariadbd
    image: docker.io/library/mariadb:latest
    name: wp-db
    ports:
    - containerPort: 80
      hostPort: 8080
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    tty: true
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: acd4d086257a467f324175ca717d3506a6de99edcc8d63fb659e7ca5d1cb4232-pvc
  - args:
    - apache2-foreground
    image: docker.io/library/wordpress:latest
    name: wp-web
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/www/html
      name: 11772dfe64ea27baa492ce9b8580cd446d045804700bd4a1551f2c2c233d13dd-pvc
  restartPolicy: Always
  volumes:
  - name: acd4d086257a467f324175ca717d3506a6de99edcc8d63fb659e7ca5d1cb4232-pvc
    persistentVolumeClaim:
      claimName: acd4d086257a467f324175ca717d3506a6de99edcc8d63fb659e7ca5d1cb4232
  - name: 11772dfe64ea27baa492ce9b8580cd446d045804700bd4a1551f2c2c233d13dd-pvc
    persistentVolumeClaim:
      claimName: 11772dfe64ea27baa492ce9b8580cd446d045804700bd4a1551f2c2c233d13dd
status: {}